USE [master]
GO
/****** Object:  Database [QLCC_V2]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE DATABASE [QLCC_V2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLCC_V2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLCC_V2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLCC_V2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLCC_V2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QLCC_V2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLCC_V2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLCC_V2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLCC_V2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLCC_V2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLCC_V2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLCC_V2] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLCC_V2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLCC_V2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLCC_V2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLCC_V2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLCC_V2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLCC_V2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLCC_V2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLCC_V2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLCC_V2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLCC_V2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLCC_V2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLCC_V2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLCC_V2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLCC_V2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLCC_V2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLCC_V2] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [QLCC_V2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLCC_V2] SET RECOVERY FULL 
GO
ALTER DATABASE [QLCC_V2] SET  MULTI_USER 
GO
ALTER DATABASE [QLCC_V2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLCC_V2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLCC_V2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLCC_V2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLCC_V2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLCC_V2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QLCC_V2', N'ON'
GO
ALTER DATABASE [QLCC_V2] SET QUERY_STORE = ON
GO
ALTER DATABASE [QLCC_V2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QLCC_V2]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DATE_TIME_KEEP]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DATE_TIME_KEEP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](max) NOT NULL,
	[DATE] [datetime2](7) NOT NULL,
	[TIME_CHECK_IN] [datetime2](7) NOT NULL,
	[TIME_CHECK_OUT] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_DATE_TIME_KEEP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORY_TIME_KEEP]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORY_TIME_KEEP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[TIME_TIME_KEEP] [decimal](18, 2) NOT NULL,
	[DATE_TIME_KEEP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_HISTORY_TIME_KEEP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LEAVE]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LEAVE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[APPROVE_USER_ID] [int] NOT NULL,
	[REASON] [nvarchar](max) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[CREATED_FOR_DAY] [datetime2](7) NOT NULL,
	[LEAVE_TYPE] [int] NOT NULL,
	[LEAVE_FORM] [int] NOT NULL,
	[LEAVE_STATUS] [int] NOT NULL,
 CONSTRAINT [PK_LEAVE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIME_KEEP]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIME_KEEP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[DATE_TIME_KEEP_ID] [int] NULL,
 CONSTRAINT [PK_TIME_KEEP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[nvarchar(50)] [nvarchar](max) NOT NULL,
	[PASSWORD] [nvarchar](max) NOT NULL,
	[FULL_NAME] [nvarchar](max) NOT NULL,
	[PHONE_NUMBER] [nvarchar](max) NOT NULL,
	[ADDRESS] [nvarchar](max) NOT NULL,
	[BIRTH_DAY] [datetime2](7) NULL,
	[COEFFICIENTS_SALARY] [float] NULL,
	[VACATION_DAY] [int] NULL,
	[NUMBER_OF_DAYS] [int] NULL,
	[SALARY] [decimal](18, 2) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_ROLE]    Script Date: 4/30/2023 1:37:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_ROLE](
	[USER_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_USER_ROLE] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20230429150128_db', N'7.0.5')
GO
/****** Object:  Index [IX_HISTORY_TIME_KEEP_USER_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_HISTORY_TIME_KEEP_USER_ID] ON [dbo].[HISTORY_TIME_KEEP]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_LEAVE_APPROVE_USER_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_LEAVE_APPROVE_USER_ID] ON [dbo].[LEAVE]
(
	[APPROVE_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_LEAVE_USER_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_LEAVE_USER_ID] ON [dbo].[LEAVE]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TIME_KEEP_DATE_TIME_KEEP_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_TIME_KEEP_DATE_TIME_KEEP_ID] ON [dbo].[TIME_KEEP]
(
	[DATE_TIME_KEEP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TIME_KEEP_USER_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_TIME_KEEP_USER_ID] ON [dbo].[TIME_KEEP]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_USER_ROLE_USER_ID]    Script Date: 4/30/2023 1:37:34 AM ******/
CREATE NONCLUSTERED INDEX [IX_USER_ROLE_USER_ID] ON [dbo].[USER_ROLE]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORY_TIME_KEEP]  WITH CHECK ADD  CONSTRAINT [FK_HISTORY_TIME_KEEP_USER_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HISTORY_TIME_KEEP] CHECK CONSTRAINT [FK_HISTORY_TIME_KEEP_USER_USER_ID]
GO
ALTER TABLE [dbo].[LEAVE]  WITH CHECK ADD  CONSTRAINT [FK_LEAVE_USER_APPROVE_USER_ID] FOREIGN KEY([APPROVE_USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[LEAVE] CHECK CONSTRAINT [FK_LEAVE_USER_APPROVE_USER_ID]
GO
ALTER TABLE [dbo].[LEAVE]  WITH CHECK ADD  CONSTRAINT [FK_LEAVE_USER_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[LEAVE] CHECK CONSTRAINT [FK_LEAVE_USER_USER_ID]
GO
ALTER TABLE [dbo].[TIME_KEEP]  WITH CHECK ADD  CONSTRAINT [FK_TIME_KEEP_DATE_TIME_KEEP_DATE_TIME_KEEP_ID] FOREIGN KEY([DATE_TIME_KEEP_ID])
REFERENCES [dbo].[DATE_TIME_KEEP] ([ID])
GO
ALTER TABLE [dbo].[TIME_KEEP] CHECK CONSTRAINT [FK_TIME_KEEP_DATE_TIME_KEEP_DATE_TIME_KEEP_ID]
GO
ALTER TABLE [dbo].[TIME_KEEP]  WITH CHECK ADD  CONSTRAINT [FK_TIME_KEEP_USER_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[TIME_KEEP] CHECK CONSTRAINT [FK_TIME_KEEP_USER_USER_ID]
GO
ALTER TABLE [dbo].[USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE_ROLE_ROLE_ID] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ROLE] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLE] CHECK CONSTRAINT [FK_USER_ROLE_ROLE_ROLE_ID]
GO
ALTER TABLE [dbo].[USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE_USER_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLE] CHECK CONSTRAINT [FK_USER_ROLE_USER_USER_ID]
GO
USE [master]
GO
ALTER DATABASE [QLCC_V2] SET  READ_WRITE 
GO
