version: '3.4'

services:
  qlcc.webclient:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
  qlcc:
    image: ${DOCKER_REGISTRY-}qlcc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Ab@123456"
      ACCEPT_EULA: "Y"